---
- name: Install necessary packages
  apt:
    name:
      - git
      - curl
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
    state: present
    update_cache: yes
