---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running
  systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create PostgreSQL database for Django
  become_user: postgres
  postgresql_db:
    name: mysite_db

- name: Create PostgreSQL user for Django
  become_user: postgres
  postgresql_user:
    name: mysite_user
    password: "mysite_password"
    #priv: "ALL"
    state: present

- name: Check Nginxpostgresql service status
  command: systemctl is-active postgresql
  register: postgresql_status
  changed_when: false

- name: Display postgresql service status
  debug:
    msg: "postgreSQL service is {{ postgresql_status.stdout }}"