- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is started and enabled
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Create PostgreSQL Database
  postgresql_db:
    name: "{{ django_db_name }}"
    state: present
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
    login_host: "{{ postgres_db_host }}"
    login_port: "{{ postgres_db_port }}"

- name: Create PostgreSQL User
  postgresql_user:
    name: "{{ django_db_user }}"
    password: "{{ django_db_password }}"
    role_attr_flags: "LOGIN"
    state: present
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
    login_host: "{{ postgres_db_host }}"
    login_port: "{{ postgres_db_port }}"

- name: Grant privileges to the user
  postgresql_user:
    name: "{{ django_db_user }}"
    db: "{{ django_db_name }}"
    role_attr_flags: "CREATEDB,CREATEROLE"
    state: present
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
    login_host: "{{ postgres_db_host }}"
    login_port: "{{ postgres_db_port }}"

- name: Grant ALL privileges on the database to the user
  postgresql_privs:
    database: "{{ django_db_name }}"
    role: "{{ django_db_user }}"
    priv: ALL
    state: present
