---
- name: Install Gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ django_venv_dir }}"
    state: present

- name: Configure Gunicorn systemd service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  notify: Reload systemd

- name: Enable and start Gunicorn service
  systemd:
    name: gunicorn
    enabled: yes
    state: started

- name: Reload systemd to pick up Gunicorn service file
  command: systemctl daemon-reload
  become: true