
# Use your server's IP address or 'localhost' if you're testing locally
your_server_name: "92.243.20.138"  # Replace with your server's IP address

# This should point to the static files directory created by the Django collectstatic command
django_static_dir: "{{ django_app_dir }}/static"  # Assuming static files are collected here

