# roles/nginx/tasks/main.yml

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx server block
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/django.conf
  notify:
    - Reload Nginx

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/django.conf
    dest: /etc/nginx/sites-enabled/django.conf
    state: link

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes
