---
- hosts: server
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_pass:

  roles:
    - role: postgres
      vars_files:
        - roles/postgres/vars/main.yml

    - role: nginx
      vars_files:
        - roles/nginx/vars/main.yml

    - role: django
      vars_files:
        - roles/django/vars/main.yml

    - role: gunicorn
      vars_files:
        - roles/gunicorn/vars/main.yml
