---
- hosts: server
  become: yes
  become_user: root
  vars:
    ansible_become_pass: "mk.sellami"
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: postgres
      vars_files:
        - roles/postgres/vars/main.yml  # Role-specific vars file
    - role: django
      vars_files:
        - roles/django/vars/main.yml  # Role-specific vars file
    - role: nginx
      vars_files:
        - roles/nginx/vars/main.yml  # Role-specific vars file

  tasks:
    - name: Ensure services are started and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - gunicorn
        - nginx

    - name: Test connectivity to the application
      wait_for:
        port: 80
        delay: 10
        timeout: 300
      when: ansible_distribution == "Ubuntu"
